### ISSUE TITLE
EPG File Format XML

### ISSUE THREAD

**Issue by madnazz** [iptv-ch/iptv-ch.github.io#1]
hello

Good thing what you're doing, but unfortunately my software doesn't support m3u - it only works with XML - there's a possibility to create an XML file as well

**Comment by redge73** [comment]
I don't manage xml file, only the owner know. sorry, don't know how to make xml file ! if help with url for auto generate xml file, maybe i can do it !

**Comment by redge73** [comment]
you need to uncompress http://myxmltv.lescigales.org/xmltv.xml.gz and extract the epg xmltv.xml with external software
