### ISSUE TITLE
How to adapt this solution for other providers

### ISSUE THREAD

**Issue by mrohner** [iptv-ch/iptv-ch.github.io#10]
My provider is "i-Way" and it would be great to have a guide on how to adapt this solution for other providers.
How to do it?

**Comment by redge73** [comment]
"Listen" channel on wireshark software while you watch and switch channel or on hardware router like avm fritzbox show url on every change channel-

Remember: 
Some isp don't use linear multicast but just ott and need user/password with their own file list ready to use like do green/salt tv with their tv solution.

**Comment by redge73** [comment]
no update

**Comment by haldi4803** [comment]
Tried this on QuickLine TV... doesn't look too good...

https://content.quickline.ch/media/v006/bkm/2021_HLS/2021_HLS.m3u8?I=125d1471-6060-4b5f-8d0f-e09302XXXXX&K=54&E=20210207213402&A=151.248.XXX.XXX&H=90221E4FB013C3C3BFE5C3653CXXXXXX
​https://drmstreamer1.cdn.quickline.ch/bpk-token/kqd0smek5aaaaaaaaelepwcaaaaaaaaaaaaidzqiqjnktbjg/0001979/GlobalManifest.m3u8
https://drmstreamer1.cdn.quickline.ch/bpk-token/kqd0smek5aaaaaaaaelepwcaaaaaaaaaaaaidzqiqjnktbjg/0001979/04.m3u8?timestamp=1612731843201    <---- This one actually works (in VLC on the same device)! But the Audio Channel is separat...
​https://drmstreamer1.cdn.quickline.ch/bpk-token/kqd0smek5aaaaaaaaelepwcaaaaaaaaaaaaidzqiqjnktbjg/0001979/09.m3u8


you also need to login with Username and password to their Homepage to actually acces the WebTV.
