### ISSUE TITLE
bvb

### ISSUE THREAD

**Issue by alfo2111** [iptv-ch/iptv-ch.github.io#12]
https://github.com/iptv-ch/iptv-ch.github.io/blob/895304ee397785ad2250b81689e5135b36e2be78/swisscom-full.m3u#L1

**Comment by redge73** [comment]
thank you alfo2111 for fire typo error, updated file swisscom-full.m3u corrected updated syntax.

old #EXTM3U url-tvg="https://xmltv.ch/xmltv/xmltv-complet.xml" 
new #EXTM3U url-tvg="#EXTM3U url-tvg="https://xmltv.ch/xmltv/xmltv-complet.xml""

**Comment by redge73** [comment]
corrected typo error
