### ISSUE TITLE
Language Telugu channels country India

### ISSUE THREAD

**Issue by DUVVI** [iptv-ch/iptv-ch.github.io#15]

**Comment by redge73** [comment]
Do you have any example of tv channel ?

**Comment by DUVVI** [comment]
gemini tv ; E tv :tv 9 ;maa tv etc

**Comment by DUVVI** [comment]
Yes

**Comment by DUVVI** [comment]
http://ip.sltv.be:8080/get.php?username=wyc5ffwnmF&password=0Ty9JVQXik&type=m3u&output=ts

**Comment by DUVVI** [comment]
EXTINF:0, group-title="Assamese",Garshom Newshttp://livestream.5centscdn.com/garshomtv/d0dbe915091d400bd8ee7f27f0791303.sdp/index.m3u8#EXTINF:0, group-title="Punjabi",GDNS Ludhianahttp://akalmultimedia.net:1935/gdnslive/gdns-live/chunklist.m3u8#EXTINF:0, group-title="Punjabi",GDNS Surreyhttp://live.agmediachandigarh.com/dukhnivaransahib/bfc254e2e8c0e9cb0f8318c493e8c78d.sdp/mono.m3u8#EXTINF:0, group-title="Telugu",Gemini Comedyhttp://mhms11.airtel.tv/wh7f454c46tw2793333123_1682756222/PLTV/88888888/224/3221226510/index.m3u8#EXTINF:0, group-title="Telugu",Gemini Lifehttp://mhms11.airtel.tv/wh7f454c46tw1615167956_298914885/PLTV/88888888/224/3221226522/index.m3u8#EXTINF:0, group-title="Telugu",Gemini Movieshttp://mhms10.airtel.tv/wh7f454c46tw1245696430_1808759359/PLTV/88888888/224/3221226528/index.m3u8#EXTINF:0, group-title="Telugu",Gemini Musichttp://mhms10.airtel.tv/wh7f454c46tw1988628988_1695487624/PLTV/88888888/224/3221226521/index.m3u8#EXTINF:0, group-title="Telugu",Gemini Newshttp://mhms10.airtel.tv/wh7f454c46tw2176596396_1844960700/PLTV/88888888/224/3221226520/index.m3u8#EXTINF:0, group-title="Telugu",Gemini TVhttp://mhms10.airtel.tv/wh7f454c46tw4133913513_809736806/PLTV/88888888/224/3221226532/index.m3u8#EXTINF:0, group-title="Telugu",Gemini TV HDhttp://mhms10.airtel.tv/wh7f454c46tw2717375159_749016567/PLTV/88888888/224/3221226517/index.m3u8#EXTINF:0, group-title="Hindi",Gemporia

**Comment by redge73** [comment]
@DUVVI 
I can't open any url ! wrong typo error.

**Comment by DUVVI** [comment]
Not working

**Comment by redge73** [comment]
out of our service
