### ISSUE TITLE
init7 m3u

### ISSUE THREAD

**Issue by labor4** [iptv-ch/iptv-ch.github.io#2]
Maybe interesting?
Couldn't test
https://api.init7.net/tvchannels.m3u

**Comment by redge73** [comment]
are you on init7 internet service provider ? if no, unpossible to watch tv channel !

**Comment by jbgtenn** [comment]
I was hoping to obtain m3u from my provider "spectrum". I have there app on phone but would like to know if there is anyway to extract the m3u or if that is something you can do? I have a working VPN that you can connect to to test if you are Interested.

**Comment by redge73** [comment]
sorry, i can't connect to your vpn, i don't know you and you don't know me.
i cancelled my virtualcomputer to expensive for connect to unknown customers.
