### ISSUE TITLE
Could Swisscom be blocking access?

### ISSUE THREAD

**Issue by oatmealm** [iptv-ch/iptv-ch.github.io#20]
Hi. Wondering if you're still maintaining this list. I was able to watch streams for a while and then it was no longer possible. I'm wondering it it's the ip list that's not up to date or am I being blocked?

Thanks!

**Comment by redge73** [comment]
Hello, it still live but it fail unfortunately on some OS like Windows 10 due some serious bug, 
It work with Standard SD format but fail with HD format and only some UHD channel are watchable 
even transedit fail to discover some channels on windows 10 (64 bit) and success with windows 7 (32bit)

RTS 1 SD
rtp://239.186.64.5:10000

RTS 1 HD
rtp://239.186.68.3:10000

But i don't know how to solve the issue. I tried some codecs but all was broken my windows !

On other side, it still work like charm on "outdated" windows 7 both channel SD/HD but i'cant watch UHD channel to old computer.
