### ISSUE TITLE
commit 8c3e6a53c615c3126823a2129e02c9248fea3fe7

### ISSUE THREAD

**Issue by W0rmsy** [iptv-ch/iptv-ch.github.io#21]
I can have access to a netplus.ch connection within my family, What Can I do to help, and how ?

**Comment by redge73** [comment]
Hello W0rmsy
If you have a wireshark (network diagnostics) configured to listen connected to SAME network/and same switch of your netplus tv box,
you can watch a channel and check ip and port and write the new ip/port here.

Any help is warm welcome.
