### ISSUE TITLE
Problems for MAG324 while receiving Swiss TV channels

### ISSUE THREAD

**Issue by mkaltaie99** [iptv-ch/iptv-ch.github.io#22]
Hello! This is Muhammad Al-Taie from Stockholm, Sweden, and I have a very serious trouble to watch ANY TV channels from e.g Switzerland. Also, I would like to tell you that those m3u files don't work at all with MAG324 box, and I would ALSO willingly receive TV5Monde channels, too. Could you please help me how to watch TV WITHOUT any subscriptions via IPTV? Thank you! ;)

**Comment by redge73** [comment]
Hello
These files are readable only on Swisscom network and connected partners with multicast group 239.x.y.z! Unusable outside of Switzerland !
IPv4 multicast range 239. is not on public internet but only private network reachable by your local ISP.

TV5Monde France Belgique Suisse (FBS) is available online
https://live.tv5monde.com/fbs.html?
