### ISSUE TITLE
Freezes and crash with Kodi / Simple IPTV

### ISSUE THREAD

**Issue by JinxCH73** [iptv-ch/iptv-ch.github.io#29]
Hi and thanks so much for the .m3u
But after a few minutes, the stream freezes and go back to Kodi menu.
I have errors on ffmpeg but anyone at Kodi forums knows what happens.
Any help ?
Everyone using .m3u flawlessly ?

PS : Using Xaomi mibox3 or Amazon Firestick with Kodi 19.4 through WLAN (no RJ45 link possible). ISP : Wingo / Swisscom (10Gbits/s)

**Comment by redge73** [comment]
With wingo.ch start ftth 500Mbit/s and no problem, added RJ-45 usb adaptator connected to mibox3 to router !

**Comment by JinxCH73** [comment]
Nice but no ethernet connection possible for me...

**Comment by redge73** [comment]
update the firmware or/and driver and/or app of your box

**Comment by JinxCH73** [comment]
Everything is up to date unfortunately...

**Comment by redge73** [comment]
if all is up to date even with older version, that mean an hardware issue from your router or your x96 !

**Comment by JinxCH73** [comment]
Which Android TV box are you using ?
Maybe my mibox3 is too old ...

**Comment by JinxCH73** [comment]
Thinking about a new Google Chromecast TV...
