### ISSUE TITLE
why accesing only with swisscom IP?

### ISSUE THREAD

**Issue by YaPaY** [iptv-ch/iptv-ch.github.io#3]
We are licenced & legal IPTV restream company in Switzerland but we can not access. It is a bit annoying

**Comment by NeySlim** [comment]
Dude. The streams come from SWISS INTERNET PROVIDERS. It's not like openbar for restream.

If you're licensed and legal, then you can surely contact professional iptv providers from swiss.

**Comment by redge73** [comment]
@YaPaY 
As said, the channels are only for Swisscom customers and partners (if you can't see stream, that mean, your company is not subscribed as partner of Swisscom/Netstream/Netplus multicast network) 
Anyway, for professional case, you have your own solution business to business (b2b)
