### ISSUE TITLE
Lot of stream are dead

### ISSUE THREAD

**Issue by sebpiller** [iptv-ch/iptv-ch.github.io#30]
On either (at least) tvopenchfr or sunrise tv, a lot of channels like OCS *, SYFY, Mangas, National Geographic, , are dead now. 

It beguns to fail around christmas I guess...

**Comment by redge73** [comment]
You are right, end of support legacy network of Sunrise (legacy netstream network) .
I don't know the channels on new network. Sorry for everybody watching on legacy ipv4 multicast tv.
Maybe on new multicast ipv6 but don't know how to do discover on it. Anyone know how to ?

**Comment by redge73** [comment]
sunrise tv from source legacy netstream.net network is closed

**Comment by redge73** [comment]
sunrise tv from source legacy netstream.net network is closed
