### ISSUE TITLE
PVR IPTV Simple Client on Kodi is eating first channel after the EXTGRP

### ISSUE THREAD

**Issue by fridrich** [iptv-ch/iptv-ch.github.io#33]
The first channel after the EXTGRP tag. I tried to read the IPTV Simple Client code and came with the following patch https://github.com/iptv-ch/iptv-ch.github.io/compare/master...fridrich:iptv-ch.github.io:master 
Just I am not sure at all whether I understood it right and whether the patch is not only masking the problem.

**Comment by redge73** [comment]
@fridrich Removed tag #EXTGRP: on all files and replaced by #EXTREM:
