### ISSUE TITLE
udp vs rtp

### ISSUE THREAD

**Issue by gva1dym** [iptv-ch/iptv-ch.github.io#4]
Hello, why do we have channels adresses in udp and some other in rtp ?

#EXTINF:-1 ,RTS1 HD

udp://@239.101.10.46:1234

Thanks for your help and clarification.

**Comment by TiagSant** [comment]
Hello,
The RTP with 1000 port, it's from Swisscom and UDP with 1234 port it's from a partner Netstream AG.
Regards.

**Comment by gva1dym** [comment]
Hello,
Ok thanks a lot for your quick answer. 
It means that we have part of the channels with 1000 port and part with 1234 port for chopenfr.
Would it be possible to have all the channels via Netstream AG (udp) ?
Thanks and best regards.

**Comment by TiagSant** [comment]
I don't know, I use Netstream feeds only on unopened channels on Swisscom. If you found RTS1 by Netstream I suppose that it's possible for every channels, but I never tried.

**Comment by gva1dym** [comment]
That’s the strange thing : even if you convert all the parameters (@, 101, 1234, etc...) it doesn’t work for the other channels.

Formuler Z8 box opens udp channels only (not rtp).

Best regards

Le 18 nov. 2019 à 17:49, Tiago Santos <notifications@github.com> a écrit :

﻿

I don't know, I use Netstream feeds only on unopened channels on Swisscom. If you found RTS1 by Netstream I suppose that it's possible for every channels, but I never tried.

**Comment by TiagSant** [comment]
This is not enough to change the protocol and the port, each configure their IP addressing in their own way. I did not search but there must exist a list with that 1234. Otherwise, it must be possible to scan the available addresses, perhaps by IGMP query incrementing the IP addresses from the same group (local multicast address, like 239.0.0.0) using Python for example or for loop with ffmpeg input. That too, I never tried.

**Comment by gva1dym** [comment]
Thanks for the explanations.
If you achieve to find something doing these steps, thank you to share.
Anyway, thanks a lot for your support.
Best regards.

**Comment by TiagSant** [comment]
You said: "Formuler Z8 box opens udp channels only (not rtp)." It's strange, it does not make sense. All multicast players will read flow passing RTP in UDP. It's seems an issue from application layer. Which player you use? You can download Kodi on Google Play Store on your box, install add-on (from "My add-ons") "PVR clients" and select "PVR IPTV Simple Client", enable and configure by placing a file or link where the m3u file is located. I prepare my own m3u file (Swisscom) I can share here, if you like, which internet provider do you have?

**Comment by gva1dym** [comment]
"...It's strange, it does not make sense. All multicast players will read flow passing RTP in UDP..."

-> Totally agree with you but the facts are exactly these ones. If you own a Formuler Z8 box and you add 2 channels to test  

1. #EXTINF:-1 ,RTS1 HD
udp://@239.101.10.46:1234

2. #EXTINF:-1 tvg-id="RTS1.ch" tvg-name="RTS un CH" tvg-logo="http://static.iptv-epg.com/ch/RTS1.ch.png" tvg-chno="92" channel-id="92",RTS1 HD
rtp://239.186.68.3:10000

You will see that the 1st one plays but not the 2nd one.
I opened a ticket at Formuler as well. They said they will investigate the issue but on their side they were note that surprised to see that udp plays but not rtp.

On the Formuler Box Z8 I use "MyTVOnline2" (Mol2), that's the best app. I know that I can use other apps to stream the Swisscom TV channels (I can also use Swisscom TV Air app directly on the Formuler Box) but my goal is to use Mol2 for all the streams (more convenient, better quality, etc...)

My Internet provider is Swisscom.

**Comment by TiagSant** [comment]
Try the netplus.m3u on this git page. We never know. Let me know if works. Otherwise, I don't know how can I solve your problem.

**Comment by gva1dym** [comment]
netplus.m3u doesn't work.
Let's wait Formuler CS if they can patch de boxes to allow them to play RTP Streams.
Thanks a lot for your help and support anyway.
Best regards.

**Comment by redge73** [comment]
@gva1dym 
try search and replace without quote "rtp://" by "udp://@" , i did this reverse because all my test done and work with vlc and this app don't understand udp protocol from Swisscom only, vlc has his/her internal stream converter, this not happen on other multicast network netstream and netplus/citycable
example: Let me know it success or fail.
rtp://239.186.68.3:10000
udp://@239.186.68.3:10000

**Comment by gva1dym** [comment]
@redge73
It doesn't work changing "rtp" by "udp" as described above by you.
As per my previous information, Formuler has patched the box to allow RTP Streams.

It works great with Sunrise and Netplus channels in RTP, Swisscom (…..:10000) it doesn't work or work very bad. Is this a wish from Swisscom ?

Best regards.

**Comment by redge73** [comment]
Try to install udpxy on your Formulez for swisscom multicast
steps to do
http://www.udpxy.com/download/udpxy/README.txt

**Comment by redge73** [comment]
no update
