### ISSUE TITLE
Add a swiss-french channel: latele.ch

### ISSUE THREAD

**Issue by ragusa87** [iptv-ch/iptv-ch.github.io#6]
Can you test and add https://latele.ch/live ?
The url is: https://latele2.vedge.infomaniak.com/livecast/latele2/manifest.m3u8
And it should be accessible from any provider as it's open, and in french.

**Comment by redge73** [comment]
Great new, i'm very happy to add new channel but the files are all multicast, i don't want to mix.
the channel la tele is over internet OTT, not same.
if you help me how to discover all tv channel over OTT, i can create a new file with all available tv channel OTT with included latele2
Thank you for your hint and help !

**Comment by ragusa87** [comment]
Hi,
Thanks for your answer,

I am sorry but I can't help you with that.. A lot of channel are well hidden or even DRM protected. (Ex: All channels from SSR are DRM Protected. See: https://www.rts.ch/entreprise/drm/9959798-la-ssr-adopte-le-cryptage-numerique.html)
