### ISSUE TITLE
epg electronic program guide website xml for community ?

### ISSUE THREAD

**Issue by redge73** [iptv-ch/iptv-ch.github.io#7]
Any epg electronic program guide website xml 10 languages as free or small fee for community   ?

**Comment by dorinilut** [comment]
I recommend using easyepg. You can find it on github. after setup with Swisscom it will generate an XML tv guide

**Comment by redge73** [comment]
> easyepg.
> after setup with Swisscom it will generate an XML tv guide

Great tool but for Linux 
@nicolasgarnier , need your help, can you host the script, so only few scripts running and files are available for the community via website or just url ?
Any help is welcome :-)

**Comment by redge73** [comment]
Found: Special thanks to https://xmltv.ch for their great job about electronic program guide for all :-)

**Comment by thilojaeggi** [comment]
xmltv.ch doesn't seem to work anymore or am I wrong?
