### ISSUE TITLE
iptv app with integrated udpxy like vlc for androidtv ?

### ISSUE THREAD

**Issue by redge73** [iptv-ch/iptv-ch.github.io#8]
iptv app with integrated microproxy like vlc for androidtv ?
I can't use TVirl because i don't have udpxy server.
What application IPTV app contain inside micro udp proxy like vlc but for iptv with epg integrated for AndroidTV ?
Any help would be appreciated

Thank your for community iptv !

**Comment by dorinilut** [comment]
I was also looking for one. in the end I ended up using a raspberry pi on which I installed tvheadend. Works really well this way. 

By the way, thanks for updating the m3u list. Do you use a specific script for that?

**Comment by redge73** [comment]
> I ended up using a raspberry pi on which I installed tvheadend. Works really well this way.
Linux too complicate for me.
 
> By the way, thanks for updating the m3u list. Do you use a specific script for that?
I use a very great scanner transedit from DVBviewer + manual checking (automatic missing too many things and wont see while channel change from scrambled to open and reverse)

**Comment by redge73** [comment]
no update
