### ISSUE TITLE
Urban Revolution TV

### ISSUE THREAD

**Issue by ea5iva** [iptv-ch/iptv-ch.github.io#9]
Buenos días,
Este canal aparece en algunas listas IPTV de España como Urban Revolution TV y en otras como uRV TV, su página web es www.urbanrevolution.es y  la URL de la emisión es https://www.urbanrevolution.es:444/live/5e6d8470a3832/index.m3u8

El logo es 
![logourbanrevolution](https://user-images.githubusercontent.com/66835149/84512390-33c1d880-acc8-11ea-9f7e-2a45272522bd.png)

**Comment by redge73** [comment]
Thank for your sharing but i'm not well understand ott url , for now is stay with multicast channel.
